const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const categorySchema = new Schema ({
    genre: {
        type: String,
        required: true,
        enum: [
            'published2020',
            'transAuthor',
            'greatFirstLine',
            'aboutBookClub',
            'olympicCity',
            'bildungsroman',
            'eyesClosed',
            'upsideDownImage',
            'withMap',
            'onlineRecommendation',
            'anthology',
            'passesBechdel',
            'sameTitleUnrelated',
            'floraFaunaAuthorName',
            'involvingSocialMedia',
            'bookOnCover',
            'medicalThriller',
            'madeupLanguage',
            'countryStartsWithC',
            'titleCaughtAttention',
            'publishedBirthMonth',
            'womanInStem',
            'award2019',
            'unknownSubject',
            'coverOnlyWords',
            'titlePun',
            'featuresSin',
            'artificialCharacter',
            'birdCover',
            'aboutWorldLeader',
            'goldSilverBronze',
            'authorWomanOfColor',
            'goodreadsFourStar',
            'meantToRead2019',
            'threeWordTitle',
            'pinkCover',
            'western',
            'byAboutJournalist',
            'banned',
            'favPrompt',
            'authorIn20s',
            'title20Twenty',
            'visionImpairedCharacter',
            'inJapan',
            'setIn20s',
            'authorWrittenMoreThan20',
            'titleMoreThan20Letters',
            'published20thCentury',
            'seriesMoreThan20',
            'characterIn20s'
        ]
    },
 }, {
    timestamps: true
});
/* const categorySchema = new Schema({
    published2020: Boolean,
    transAuthor: Boolean,
    greatFirstLine: Boolean,
    aboutBookClub: Boolean,
    olympicCity: Boolean,
    bildungsroman: Boolean,
    eyesClosed: Boolean,
    upsideDownImage: Boolean,
    withMap: Boolean,
    onlineRecommendation: Boolean,
    anthology: Boolean,
    passesBechdel: Boolean,
    sameTitleUnrelated: Boolean,
    floraFaunaAuthorName: Boolean,
    involvingSocialMedia: Boolean,
    bookOnCover: Boolean,
    medicalThriller: Boolean,
    madeupLanguage: Boolean,
    countryStartsWithC: Boolean,
    titleCaughtAttention: Boolean,
    publishedBirthMonth: Boolean,
    womanInStem: Boolean,
    award2019: Boolean,
    unknownSubject: Boolean,
    coverOnlyWords: Boolean,
    titlePun: Boolean,
    featuresSin: Boolean,
    artificialCharacter: Boolean,
    birdCover: Boolean,
    aboutWorldLeader: Boolean,
    goldSilverBronze: Boolean,
    authorWomanOfColor: Boolean,
    goodreadsFourStar: Boolean,
    meantToRead2019: Boolean,
    threeWordTitle: Boolean,
    pinkCover: Boolean,
    western: Boolean,
    byAboutJournalist: Boolean,
    banned: Boolean,
    favPrompt: Boolean,
    authorIn20s: Boolean,
    title20Twenty: Boolean,
    visionImpairedCharacter: Boolean,
    inJapan: Boolean,
    setIn20s: Boolean,
    authorWrittenMoreThan20: Boolean,
    titleMoreThan20Letters: Boolean,
    published20thCentury: Boolean,
    seriesMoreThan20: Boolean,
    characterIn20s: Boolean
}, {
    timestamps: true
}); */

module.exports = mongoose.model('Category', categorySchema);