const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const categorySchema = new Schema ({
    genre: {
        type: String,
        required: true,
        enum: [
            'A book published in 2020',
            'A book by a trans or nonbinary author',
            'A book with a great first line',
            'A book about a book club',
            'A book set in a city that has hosted the Olympics',
            'A bildungsroman',
            'The first book you touch on a shelf with your eyes closed',
            'A book with an upside-down image on the cover',
            'A book with a map',
            'A book recommended by your favorite blog, vlog, podcast, or online book club',
            'An anthology',
            'A book that passes the Bechdel test',
            'A book with the same title as a movie or TV show, but is unrelated',
            'A book by an author with flora or fauna in their name',
            'A book about or involving social media',
            'A book that has a book on the cover',
            'A medical thriller',
            'A book with a made-up language',
            'A book set in a country beginning with "C" ',
            'A book you picked up because the title caught your attention',
            'A book published the month of your birthday',
            'A book about or by a woman in STEM',
            'A book that won an award in 2019',
            'A book on a subject you know nothing about',
            'A book with only words on the cover, no images or graphics',
            'A book with a pun in the title',
            'A book featuring one of the seven deadly sins',
            'artificialCharacter',
            'A book with a bird on the cover',
            'A fiction or nonfiction book about a world leader',
            'A book with "gold," "silver," or "bronze" in the title',
            'A book by a WOC',
            'A book with at least a 4-star rating on Goodreads',
            'A book you meant to read in 2019',
            'A book with a 3-word title',
            'A book with a pink cover',
            'A Western',
            'A book by or about a journalist',
            'A banned book',
            'Your favorite prompt from a past POPSUGAR Reading Challenge',
            'A book written by an author in their 20s',
            'A book with "20" or "twenty" in the title',
            'A book with a character with a vision impairment or enhancement (a nod to 20/20 vision)',
            'A book set in Japan, host of the 2020 Olympics',
            'A book set in the 1920s',
            'A book written by an author who has written more than 20 books',
            'A book with more than 20 letters in its title',
            'A book published in the 20th century',
            'A book from a series with more than 20 books',
            'A book with a main character in their 20s'
        ]
    },
 }, {
    timestamps: true
});
/* const categorySchema = new Schema({
    published2020: Boolean,
    transAuthor: Boolean,
    greatFirstLine: Boolean,
    aboutBookClub: Boolean,
    olympicCity: Boolean,
    bildungsroman: Boolean,
    eyesClosed: Boolean,
    upsideDownImage: Boolean,
    withMap: Boolean,
    onlineRecommendation: Boolean,
    anthology: Boolean,
    passesBechdel: Boolean,
    sameTitleUnrelated: Boolean,
    floraFaunaAuthorName: Boolean,
    involvingSocialMedia: Boolean,
    bookOnCover: Boolean,
    medicalThriller: Boolean,
    madeupLanguage: Boolean,
    countryStartsWithC: Boolean,
    titleCaughtAttention: Boolean,
    publishedBirthMonth: Boolean,
    womanInStem: Boolean,
    award2019: Boolean,
    unknownSubject: Boolean,
    coverOnlyWords: Boolean,
    titlePun: Boolean,
    featuresSin: Boolean,
    artificialCharacter: Boolean,
    birdCover: Boolean,
    aboutWorldLeader: Boolean,
    goldSilverBronze: Boolean,
    authorWomanOfColor: Boolean,
    goodreadsFourStar: Boolean,
    meantToRead2019: Boolean,
    threeWordTitle: Boolean,
    pinkCover: Boolean,
    western: Boolean,
    byAboutJournalist: Boolean,
    banned: Boolean,
    favPrompt: Boolean,
    authorIn20s: Boolean,
    title20Twenty: Boolean,
    visionImpairedCharacter: Boolean,
    inJapan: Boolean,
    setIn20s: Boolean,
    authorWrittenMoreThan20: Boolean,
    titleMoreThan20Letters: Boolean,
    published20thCentury: Boolean,
    seriesMoreThan20: Boolean,
    characterIn20s: Boolean
}, {
    timestamps: true
}); */

module.exports = mongoose.model('Category', categorySchema);